### ISSUE TITLE
Random with Exclusions

### ISSUE THREAD

**Issue by egbuck** [zeobviouslyfakeacc/InterloperRegionSelection#1]
This is a neat mod.  One idea would be adding a feature where you could still have it randomly choose, but exclude certain regions.  Perhaps this would be a nice feature for those starting a new run that want a different spawn then they've had in the past, or if they want to avoid certain regions like Blackrock.  But I know making a GUI or something for this would be more involved.

**Comment by ds5678** [comment]
The amount of work involved is too high to justify. Just flip a coin, roll a di, or use an online random number generator.
